<?php declare(strict_types=1);

namespace Tests\Traits;

use App\Models\Permission;
use App\Models\Role;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Src\RBAC\Services\AuthService;

/**
 * Trait giúp thiết lập RBAC cho các feature/API tests
 */
trait RbacTestTrait
{
    /**
     * Bản đồ alias -> permissions giúp test hiểu các mã legacy
     */
    /**
     * Tạo user gắn với tenant mới
     */
    protected function makeTenantUser(array $overrides = []): User
    {
        $tenant = Tenant::factory()->create();

        return User::factory()->create(array_merge([
            'tenant_id' => $tenant->id,
            'password' => Hash::make('password123'),
            'is_active' => true,
        ], $overrides));
    }

    /**
     * Gán role hệ thống cho user
     */
    protected function grantRole(User $user, string $roleCode): Role
    {
        $role = Role::firstOrCreate([
            'name' => $roleCode,
        ], [
            'scope' => Role::SCOPE_SYSTEM,
            'allow_override' => false,
            'description' => sprintf('Assigned via test helper (%s)', $roleCode),
            'is_active' => true,
            'tenant_id' => $user->tenant_id,
        ]);

        $user->roles()->syncWithoutDetaching($role->id);

        return $role;
    }

    /**
     * Gán permissions (và alias nếu cần) cho user qua một role temporary
     */
    protected function grantPermissionsByCode(User $user, array $permissionCodes): Role
    {
        $resolved = $this->resolvePermissionCodes($permissionCodes);
        $permissionIds = [];

        foreach ($resolved as $code) {
            $permission = $this->ensurePermissionRecord($code);
            $permissionIds[] = $permission->id;
        }

        $roleName = 'rbac-test-role-' . uniqid();
        $role = Role::create([
            'name' => $roleName,
            'scope' => Role::SCOPE_SYSTEM,
            'description' => 'Temporary test role',
            'allow_override' => false,
            'is_active' => true,
            'tenant_id' => $user->tenant_id,
        ]);

        $role->permissions()->syncWithoutDetaching($permissionIds);
        $user->roles()->syncWithoutDetaching($role->id);

        return $role;
    }

    /**
     * Tạo user tenant và authenticate kèm permissions, trả về token+user
     *
     * @param array $permissionCodes
     * @param array $options
     * @return array{user: User, token: string}
     */
    protected function actingAsWithPermissions(array $permissionCodes = [], array $options = []): array
    {
        $attributes = $options['attributes'] ?? [];
        $roles = $options['roles'] ?? [];

        $user = $this->makeTenantUser($attributes);

        if (!empty($permissionCodes)) {
            $this->grantPermissionsByCode($user, $permissionCodes);
        }

        foreach ($roles as $roleName) {
            $this->grantRole($user, $roleName);
        }

        $tokens = $this->authenticateTenantUser($user);

        return [
            'user' => $user,
            'token' => $tokens['token'],
            'sanctum_token' => $tokens['sanctum_token'],
        ];
    }

    /**
     * Backwards-compatible wrapper
     */
    protected function actingAsTenantUserWithPermissions(array $permissionCodes = [], array $options = []): array
    {
        return $this->actingAsWithPermissions($permissionCodes, $options);
    }

    /**
     * Đăng nhập user và đặt header Authorization
     */
    private function authenticateTenantUser(User $user): array
    {
        $authService = app(AuthService::class);
        $token = $authService->createTokenForUser($user);
        $sanctumToken = $user->createToken('rbac-testing-token')->plainTextToken;
        $this->withHeader('Authorization', 'Bearer ' . $sanctumToken);

        return [
            'token' => $token,
            'sanctum_token' => $sanctumToken,
        ];
    }

    /**
     * Tạo hoặc nạp permission record
     */
    private function ensurePermissionRecord(string $code): Permission
    {
        [$module, $action] = $this->splitPermissionCode($code);

        return Permission::firstOrCreate(
            ['code' => $code],
            [
                'module' => $module,
                'action' => $action,
                'description' => 'Generated by RBAC test helper',
            ]
        );
    }

    /**
     * Expand alias sang các permission thực thi
     */
    private function resolvePermissionCodes(array $permissionCodes): array
    {
        $resolved = [];

        $map = config('rbac.permission_aliases', []);

        foreach ($permissionCodes as $code) {
            $resolved[] = $code;

            foreach ($map[$code] ?? [] as $mapped) {
                $resolved[] = $mapped;
            }
        }

        return array_values(array_unique($resolved));
    }

    /**
     * Tách module/action từ code
     */
    private function splitPermissionCode(string $code): array
    {
        $parts = explode('.', $code, 2);
        $module = $parts[0];
        $action = $parts[1] ?? 'access';

        return [$module, $action];
    }
}
