module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:sonarjs/recommended'
  ],
  plugins: ['sonarjs'],
  rules: {
    'sonarjs/cognitive-complexity': 'error',
    'sonarjs/no-duplicate-string': ['error', { threshold: 3 }],
    'sonarjs/no-identical-functions': 'error',
    'sonarjs/no-redundant-boolean': 'error',
    'sonarjs/no-unused-collection': 'error',
    'sonarjs/prefer-immediate-return': 'error',
    'sonarjs/prefer-single-boolean-return': 'error',
    'sonarjs/no-duplicate-string': ['error', { 
      threshold: 3,
      ignoreStrings: [
        'ZenaManage',
        'Dashboard',
        'Projects',
        'Tasks',
        'Team',
        'Reports',
        'Settings',
        'Profile',
        'Logout',
        'Login',
        'Register',
        'Password',
        'Email',
        'Name',
        'Description',
        'Status',
        'Priority',
        'Created',
        'Updated',
        'Deleted',
        'Success',
        'Error',
        'Warning',
        'Info',
        'Loading',
        'Save',
        'Cancel',
        'Edit',
        'Delete',
        'View',
        'Create',
        'Update',
        'Search',
        'Filter',
        'Sort',
        'Export',
        'Import',
        'Download',
        'Upload',
        'Submit',
        'Reset',
        'Clear',
        'Close',
        'Open',
        'Show',
        'Hide',
        'Toggle',
        'Select',
        'Choose',
        'Add',
        'Remove',
        'Yes',
        'No',
        'OK',
        'Cancel',
        'Confirm',
        'Back',
        'Next',
        'Previous',
        'First',
        'Last',
        'Home',
        'About',
        'Contact',
        'Help',
        'Support',
        'FAQ',
        'Terms',
        'Privacy',
        'Policy',
        'Copyright',
        'All Rights Reserved',
        'Version',
        'Build',
        'Release',
        'Beta',
        'Alpha',
        'Stable',
        'Development',
        'Production',
        'Testing',
        'Staging',
        'Local',
        'Server',
        'Client',
        'API',
        'REST',
        'GraphQL',
        'JSON',
        'XML',
        'HTML',
        'CSS',
        'JavaScript',
        'TypeScript',
        'React',
        'Vue',
        'Angular',
        'Node.js',
        'PHP',
        'Laravel',
        'MySQL',
        'PostgreSQL',
        'MongoDB',
        'Redis',
        'Cache',
        'Session',
        'Cookie',
        'Token',
        'Auth',
        'Authentication',
        'Authorization',
        'Permission',
        'Role',
        'User',
        'Admin',
        'Guest',
        'Member',
        'Owner',
        'Manager',
        'Developer',
        'Designer',
        'Tester',
        'Analyst',
        'Consultant',
        'Contractor',
        'Employee',
        'Staff',
        'Team',
        'Group',
        'Organization',
        'Company',
        'Business',
        'Enterprise',
        'Startup',
        'Project',
        'Task',
        'Issue',
        'Bug',
        'Feature',
        'Enhancement',
        'Improvement',
        'Fix',
        'Patch',
        'Update',
        'Upgrade',
        'Migration',
        'Deployment',
        'Release',
        'Version',
        'Branch',
        'Commit',
        'Merge',
        'Pull Request',
        'Code Review',
        'Testing',
        'Unit Test',
        'Integration Test',
        'E2E Test',
        'Performance Test',
        'Security Test',
        'Load Test',
        'Stress Test',
        'Smoke Test',
        'Regression Test',
        'Acceptance Test',
        'Manual Test',
        'Automated Test',
        'Test Case',
        'Test Suite',
        'Test Plan',
        'Test Strategy',
        'Test Coverage',
        'Quality Assurance',
        'Quality Control',
        'Bug Report',
        'Issue Tracker',
        'Project Management',
        'Task Management',
        'Time Tracking',
        'Resource Management',
        'Risk Management',
        'Change Management',
        'Configuration Management',
        'Release Management',
        'Incident Management',
        'Problem Management',
        'Service Management',
        'ITIL',
        'Agile',
        'Scrum',
        'Kanban',
        'Waterfall',
        'DevOps',
        'CI/CD',
        'Continuous Integration',
        'Continuous Deployment',
        'Continuous Delivery',
        'Build Pipeline',
        'Deployment Pipeline',
        'Release Pipeline',
        'Monitoring',
        'Logging',
        'Alerting',
        'Metrics',
        'Analytics',
        'Reporting',
        'Dashboard',
        'KPI',
        'SLA',
        'SLO',
        'SLI',
        'MTTR',
        'MTBF',
        'Availability',
        'Reliability',
        'Scalability',
        'Performance',
        'Security',
        'Compliance',
        'Audit',
        'Backup',
        'Recovery',
        'Disaster Recovery',
        'Business Continuity',
        'High Availability',
        'Load Balancing',
        'Clustering',
        'Replication',
        'Sharding',
        'Partitioning',
        'Indexing',
        'Optimization',
        'Tuning',
        'Profiling',
        'Debugging',
        'Troubleshooting',
        'Root Cause Analysis',
        'Post-mortem',
        'Lessons Learned',
        'Best Practices',
        'Standards',
        'Guidelines',
        'Conventions',
        'Patterns',
        'Architecture',
        'Design',
        'Implementation',
        'Development',
        'Coding',
        'Programming',
        'Software Engineering',
        'System Administration',
        'Database Administration',
        'Network Administration',
        'Security Administration',
        'User Administration',
        'Access Control',
        'Identity Management',
        'Single Sign-On',
        'Multi-Factor Authentication',
        'Two-Factor Authentication',
        'Biometric Authentication',
        'Certificate',
        'Encryption',
        'Decryption',
        'Hashing',
        'Salt',
        'Key',
        'Public Key',
        'Private Key',
        'Digital Signature',
        'Digital Certificate',
        'SSL',
        'TLS',
        'HTTPS',
        'HTTP',
        'FTP',
        'SFTP',
        'SSH',
        'Telnet',
        'SMTP',
        'POP3',
        'IMAP',
        'DNS',
        'DHCP',
        'TCP',
        'UDP',
        'IP',
        'IPv4',
        'IPv6',
        'MAC',
        'Ethernet',
        'WiFi',
        'Bluetooth',
        'USB',
        'HDMI',
        'VGA',
        'DVI',
        'DisplayPort',
        'Thunderbolt',
        'Firewire',
        'Serial',
        'Parallel',
        'SCSI',
        'SATA',
        'IDE',
        'NVMe',
        'SSD',
        'HDD',
        'RAM',
        'ROM',
        'CPU',
        'GPU',
        'Motherboard',
        'Power Supply',
        'Cooling',
        'Fan',
        'Heat Sink',
        'Thermal Paste',
        'Case',
        'Chassis',
        'Rack',
        'Cabinet',
        'Data Center',
        'Server Room',
        'Network Closet',
        'Wiring',
        'Cable',
        'Fiber',
        'Copper',
        'Wireless',
        'Radio',
        'Microwave',
        'Satellite',
        'Cellular',
        '3G',
        '4G',
        '5G',
        'LTE',
        'WiMAX',
        'CDMA',
        'GSM',
        'UMTS',
        'HSPA',
        'EVDO',
        'Edge',
        'GPRS',
        'EDGE',
        'HSDPA',
        'HSUPA',
        'HSPA+',
        'LTE-A',
        'LTE-Pro',
        '5G NR',
        '5G SA',
        '5G NSA',
        '5G mmWave',
        '5G Sub-6',
        '5G C-Band',
        '5G Low-Band',
        '5G Mid-Band',
        '5G High-Band',
        '5G Ultra-High-Band',
        '5G Terahertz',
        '5G Visible Light',
        '5G LiFi',
        '5G VLC',
        '5G OWC',
        '5G FSO',
        '5G RF',
        '5G Optical',
        '5G Photonic',
        '5G Quantum',
        '5G AI',
        '5G ML',
        '5G Edge',
        '5G Cloud',
        '5G Fog',
        '5G Mist',
        '5G Dew',
        '5G IoT',
        '5G IIoT',
        '5G IoE',
        '5G IoMT',
        '5G IoV',
        '5G IoST',
        '5G IoNT',
        '5G IoCT',
        '5G IoHT',
        '5G IoET',
        '5G IoPT',
        '5G IoRT',
        '5G IoAT',
        '5G IoBT',
        '5G IoCT',
        '5G IoDT',
        '5G IoET',
        '5G IoFT',
        '5G IoGT',
        '5G IoHT',
        '5G IoIT',
        '5G IoJT',
        '5G IoKT',
        '5G IoLT',
        '5G IoMT',
        '5G IoNT',
        '5G IoOT',
        '5G IoPT',
        '5G IoQT',
        '5G IoRT',
        '5G IoST',
        '5G IoT',
        '5G IoUT',
        '5G IoVT',
        '5G IoWT',
        '5G IoXT',
        '5G IoYT',
        '5G IoZT'
      ]
    }]
  },
  env: {
    browser: true,
    es2021: true,
    node: true
  },
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module'
  }
};
