/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user information
         * @description Returns authenticated user information, permissions, and abilities. Unified endpoint for both React and Blade.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                            /**
                             * @description List of permissions for the user's role
                             * @example [
                             *       "projects.view",
                             *       "tasks.create",
                             *       "dashboard.view"
                             *     ]
                             */
                            permissions: string[];
                            /**
                             * @description User abilities (tenant-scoped or admin)
                             * @example [
                             *       "tenant"
                             *     ]
                             */
                            abilities: ("tenant" | "admin")[];
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get navigation menu
         * @description Returns navigation items filtered by user permissions. Unified endpoint for both React and Blade to read the same navigation schema.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Navigation items with user context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                            /**
                             * @description List of permissions for the user's role
                             * @example [
                             *       "projects.view",
                             *       "tasks.create",
                             *       "dashboard.view"
                             *     ]
                             */
                            permissions: string[];
                            /**
                             * @description User abilities (tenant-scoped or admin)
                             * @example [
                             *       "tenant"
                             *     ]
                             */
                            abilities: ("tenant" | "admin")[];
                            /** @description Filtered navigation items based on user permissions */
                            navigation: components["schemas"]["NavItem"][];
                            admin_access?: {
                                /** @description Whether user is a super admin */
                                is_super_admin?: boolean;
                                /** @description Whether user is an org admin (tenant-scoped admin) */
                                is_org_admin?: boolean;
                            };
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Get paginated list of projects for the authenticated user's tenant
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    status?: "planning" | "active" | "on_hold" | "completed" | "cancelled";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Project"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * Create project
         * @description Create a new project
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreate"];
                };
            };
            responses: {
                /** @description Project created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Project"];
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Project"];
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tasks
         * @description Get paginated list of tasks for the authenticated user's tenant
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    status?: "backlog" | "todo" | "in_progress" | "review" | "done" | "cancelled";
                    project_id?: string | null;
                    priority?: "low" | "medium" | "high" | "urgent" | null;
                    assignee_id?: string | null;
                    search?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Task"][];
                            meta?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * Create task
         * @description Create a new task
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreate"];
                };
            };
            responses: {
                /** @description Task created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Task"];
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Task"];
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        /**
         * Update task
         * @description Update an existing task
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdate"];
                };
            };
            responses: {
                /** @description Task updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Task"];
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete task
         * @description Delete a task
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Partially update task
         * @description Partially update an existing task
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdate"];
                };
            };
            responses: {
                /** @description Task updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Task"];
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/app/tasks/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move task to new status
         * @description Move a task to a new status (Kanban drag-drop). Supports optimistic concurrency control via version field.
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Target status for the task
                         * @enum {string}
                         */
                        to_status: "backlog" | "todo" | "in_progress" | "review" | "done" | "cancelled";
                        /** @description Task ID to place this task before (for ordering) */
                        before_id?: string | null;
                        /** @description Task ID to place this task after (for ordering) */
                        after_id?: string | null;
                        /** @description Optional reason for the status change */
                        reason?: string | null;
                        /** @description Task version for optimistic concurrency control */
                        version?: number | null;
                    };
                };
            };
            responses: {
                /** @description Task moved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Task"];
                            /** @description Optional warning message (e.g., if version mismatch was resolved) */
                            warning?: string | null;
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                /** @description Conflict - version mismatch or concurrent modification */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/app/tasks/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk delete tasks
         * @description Delete multiple tasks at once
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Array of task IDs to delete */
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Tasks deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: {
                                deleted_count?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/tasks/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk update task status
         * @description Update status for multiple tasks at once
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Array of task IDs to update */
                        ids: string[];
                        /**
                         * @description New status for all tasks
                         * @enum {string}
                         */
                        status: "backlog" | "todo" | "in_progress" | "review" | "done" | "cancelled";
                    };
                };
            };
            responses: {
                /** @description Tasks updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: {
                                updated_count?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/tasks/bulk-assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk assign tasks
         * @description Assign multiple tasks to a user at once
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description Idempotency key for write operations (POST, PUT, PATCH).
                     *     Format: {resource}_{action}_{timestamp}_{nonce}
                     *     Example: project_create_1705123456789_abc123xyz
                     * @example project_create_1705123456789_abc123xyz
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Array of task IDs to assign */
                        ids: string[];
                        /** @description User ID to assign tasks to */
                        assignee_id: string;
                    };
                };
            };
            responses: {
                /** @description Tasks assigned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: {
                                assigned_count?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Login and receive authentication token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authentication successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                token?: string;
                                /** @example Bearer */
                                token_type?: string;
                                expires_in?: number;
                                user?: components["schemas"]["User"];
                            };
                        };
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 01K83FPK5XGPXF3V7ANJQRGX5X */
            id: string;
            /** @example John Doe */
            name: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /**
             * @description Tenant ID for tenant-scoped users, null for super admins
             * @example 01K83FPK5XGPXF3V7ANJQRGX5Y
             */
            tenant_id?: string | null;
            /**
             * @example member
             * @enum {string}
             */
            role: "super_admin" | "org_admin" | "admin" | "pm" | "member" | "client";
        };
        NavItem: {
            /**
             * @description Route path for navigation
             * @example /app/dashboard
             */
            path: string;
            /**
             * @description Display label for navigation item
             * @example Dashboard
             */
            label: string;
            /**
             * @description Icon name (matches icon component library)
             * @example Gauge
             */
            icon: string;
            /**
             * @description Required permission to view this navigation item
             * @example dashboard.view
             */
            perm: string;
            /**
             * @description Whether this is an admin navigation item
             * @default false
             */
            admin: boolean;
            /**
             * @description Whether this is a system-only navigation item (super admin only)
             * @default false
             */
            system_only: boolean;
            /**
             * @description Whether this is a tenant-scoped admin item (org admin)
             * @default false
             */
            tenant_scoped: boolean;
        };
        Project: {
            id?: string;
            name?: string;
            description?: string | null;
            /** @enum {string} */
            status?: "planning" | "active" | "on_hold" | "completed" | "cancelled";
            progress_pct?: number;
            tenant_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProjectCreate: {
            name: string;
            description?: string;
            /**
             * @default planning
             * @enum {string}
             */
            status: "planning" | "active" | "on_hold" | "completed" | "cancelled";
        };
        Task: {
            id?: string;
            name?: string;
            description?: string | null;
            /** @enum {string} */
            status?: "backlog" | "todo" | "in_progress" | "review" | "done" | "cancelled";
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            project_id?: string | null;
            assignee_id?: string | null;
            tenant_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TaskCreate: {
            name: string;
            description?: string | null;
            /**
             * @default backlog
             * @enum {string}
             */
            status: "backlog" | "todo" | "in_progress" | "review" | "done" | "cancelled";
            /**
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            project_id?: string | null;
            assignee_id?: string | null;
            /** Format: date-time */
            due_date?: string | null;
        };
        TaskUpdate: {
            name?: string;
            description?: string | null;
            /** @enum {string} */
            status?: "backlog" | "todo" | "in_progress" | "review" | "done" | "cancelled";
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            project_id?: string | null;
            assignee_id?: string | null;
            /** Format: date-time */
            due_date?: string | null;
        };
        ErrorResponse: {
            error: {
                /** @description Unique error identifier for correlation */
                id: string;
                /** @description Error code */
                code: string;
                /** @description Human-readable error message */
                message: string;
                /** @description Additional error details */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        PaginationMeta: {
            total?: number;
            per_page?: number;
            current_page?: number;
            last_page?: number;
            from?: number | null;
            to?: number | null;
        };
        ErrorEnvelope: {
            error: {
                /**
                 * @description Unique error identifier for correlation
                 * @example req_abc12345
                 */
                id: string;
                /**
                 * @description Error code following pattern E{HTTP_CODE}.{CATEGORY}
                 * @example E422.VALIDATION
                 */
                code: string;
                /**
                 * @description Human-readable error message
                 * @example Validation failed
                 */
                message: string;
                /** @description Additional error details */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Unauthorized - Authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "id": "req_xyz789",
                 *         "code": "E401.AUTHENTICATION",
                 *         "message": "Authentication required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "id": "req_xyz789",
                 *         "code": "E404.NOT_FOUND",
                 *         "message": "Resource not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "id": "req_xyz789",
                 *         "code": "E422.VALIDATION",
                 *         "message": "Validation failed",
                 *         "details": {
                 *           "validation": {
                 *             "name": [
                 *               "The name field is required."
                 *             ]
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "id": "req_xyz789",
                 *         "code": "E500.SERVER_ERROR",
                 *         "message": "Internal server error"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /**
         * @description Idempotency key for write operations (POST, PUT, PATCH).
         *     Format: {resource}_{action}_{timestamp}_{nonce}
         *     Example: project_create_1705123456789_abc123xyz
         * @example project_create_1705123456789_abc123xyz
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

/**
 * PR #4: Helper types and utilities for API client
 */

// Extract response types from paths
export type ApiResponse<T> = {
  success?: boolean;
  ok?: boolean;
  data?: T;
  message?: string;
  error?: {
    code: string;
    message: string;
    details?: any;
    traceId?: string;
  };
  meta?: {
    current_page?: number;
    per_page?: number;
    total?: number;
    last_page?: number;
    from?: number;
    to?: number;
  };
  links?: {
    first?: string;
    last?: string;
    prev?: string;
    next?: string;
  };
};

export type PaginatedResponse<T> = ApiResponse<T[]> & {
  meta: {
    current_page: number;
    per_page: number;
    total: number;
    last_page: number;
    from?: number;
    to?: number;
  };
  links?: {
    first?: string;
    last?: string;
    prev?: string;
    next?: string;
  };
};

/**
 * Generate idempotency key for API requests
 * Format: {resource}_{action}_{timestamp}_{nonce}
 * 
 * @param resource - Resource name (e.g., 'project', 'task')
 * @param action - Action name (e.g., 'create', 'update')
 * @returns Idempotency key string
 */
export function generateIdempotencyKey(resource: string, action: string): string {
  const timestamp = Date.now();
  const nonce = Math.random().toString(36).substring(2, 15);
  return `${resource}_${action}_${timestamp}_${nonce}`;
}

// Type helpers for extracting path types
export type Paths = paths;
export type PathMethods<T extends keyof paths> = keyof paths[T];
export type PathResponse<T extends keyof paths, M extends PathMethods<T>> = 
  paths[T][M] extends { responses: infer R } 
    ? R extends { 200: { content: { 'application/json': infer D } } }
      ? D
      : never
    : never;
