<?php declare(strict_types=1);

/**
 * Regenerates docs/owner-governance/legacy-work-ids.txt from
 * OPERATIONAL_GAP_REGISTER.md — every GAP-NNN id present in the register
 * as of the owner-governance effective date is exempt from gate-ordering
 * enforcement (Task 9). This is a ONE-TIME generation script, re-run only
 * if the effective date itself is deliberately moved (it should not be).
 */

$repoRoot = dirname(__DIR__, 2);
$registerPath = $repoRoot . '/OPERATIONAL_GAP_REGISTER.md';
$outPath = $repoRoot . '/docs/owner-governance/legacy-work-ids.txt';

$content = file_get_contents($registerPath);
preg_match_all('/\bGAP-\d{3}\b/', $content, $matches);
$ids = array_values(array_unique($matches[0]));
sort($ids);

$lines = [
    '# Generated by scripts/ssot/generate_legacy_work_ids.php from OPERATIONAL_GAP_REGISTER.md',
    '# Effective date: see docs/owner-governance/enforcement-boundary.yml',
    '# Reason: pre-dates the owner-governance system (2026-08-04) — exempt from',
    '# gate-ordering enforcement, NOT exempt from packet structural validity',
    '# (any packet that DOES exist for one of these IDs must still be schema-valid).',
];
foreach ($ids as $id) {
    $lines[] = $id;
}

file_put_contents($outPath, implode("\n", $lines) . "\n");
echo 'Wrote ' . count($ids) . " legacy work IDs to {$outPath}\n";
