<?php declare(strict_types=1);

namespace Tests\Support\SSOT;

use App\Models\DashboardMetric;
use App\Models\DashboardMetricValue;
use App\Models\Document;
use App\Models\Permission;
use App\Models\Project;
use App\Models\Rfi;
use App\Models\Role;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Support\Str;
use Tests\Traits\TenantUserFactoryTrait;

trait FixtureFactory
{
    use TenantUserFactoryTrait;

    protected function createTenant(array $attributes = []): Tenant
    {
        return Tenant::factory()->create(array_merge([
            'name' => 'SSOT Tenant',
            'domain' => 'ssot-' . Str::lower((string) Str::ulid()) . '.example.test',
            'status' => 'active',
            'is_active' => true,
        ], $attributes));
    }

    protected function createTenantUserWithRbac(
        Tenant $tenant,
        string $appRole = 'member',
        string $rbacRole = 'member',
        array $permissions = [],
        array $userOverrides = []
    ): User {
        $user = $this->createTenantUser($tenant, array_merge([
            'name' => 'SSOT User',
            'email' => 'ssot+' . Str::lower((string) Str::ulid()) . '@example.test',
            'role' => $appRole,
        ], $userOverrides), [$rbacRole], $permissions);

        $role = Role::firstOrCreate(
            ['name' => $rbacRole],
            [
                'scope' => Role::SCOPE_SYSTEM,
                'allow_override' => false,
                'description' => Str::title(str_replace('_', ' ', $rbacRole)),
                'is_active' => true,
            ]
        );

        $permissionIds = [];
        foreach ($permissions as $permissionCode) {
            [$module, $action] = array_pad(explode('.', $permissionCode, 2), 2, '*');
            $permission = Permission::firstOrCreate(
                ['code' => $permissionCode],
                [
                    'name' => $permissionCode,
                    'module' => $module,
                    'action' => $action,
                    'description' => 'Generated by SSOT fixture helper',
                ]
            );
            $permissionIds[] = $permission->id;
        }

        if ($permissionIds !== []) {
            $role->permissions()->syncWithoutDetaching($permissionIds);
        }

        $user->roles()->syncWithoutDetaching([$role->id]);
        $user->systemRoles()->syncWithoutDetaching([$role->id]);

        return $user;
    }

    protected function createProjectForTenant(Tenant $tenant, ?User $owner = null, array $attributes = []): Project
    {
        $owner ??= User::factory()->create([
            'tenant_id' => $tenant->id,
        ]);

        return Project::factory()->create(array_merge([
            'tenant_id' => $tenant->id,
            'pm_id' => $owner->id,
            'created_by' => $owner->id,
            'code' => 'PRJ-' . strtoupper(Str::random(8)),
            'name' => 'SSOT Project',
            'budget_planned' => 0,
            'budget_actual' => 0,
            'budget_total' => 0,
            'progress' => 0,
        ], $attributes));
    }

    protected function createDashboardMetricWithValue(
        Tenant $tenant,
        ?Project $project = null,
        array $metricAttributes = [],
        array $valueAttributes = []
    ): array {
        $metric = DashboardMetric::create(array_merge([
            'tenant_id' => $tenant->id,
            'project_id' => $project?->id,
            'code' => 'metric_' . Str::lower(Str::random(8)),
            'name' => 'SSOT Metric',
            'category' => DashboardMetric::CATEGORY_PERFORMANCE,
            'type' => 'gauge',
            'unit' => '%',
            'is_active' => true,
            'permissions' => ['project_manager'],
        ], $metricAttributes));

        $value = DashboardMetricValue::create(array_merge([
            'metric_id' => $metric->id,
            'tenant_id' => $tenant->id,
            'project_id' => $project?->id,
            'value' => 0,
            'recorded_at' => now(),
            'metadata' => [],
        ], $valueAttributes));

        return ['metric' => $metric, 'value' => $value];
    }

    protected function createRfiFor(Tenant $tenant, Project $project, User $user, array $attributes = []): Rfi
    {
        return Rfi::factory()->create(array_merge([
            'tenant_id' => $tenant->id,
            'project_id' => $project->id,
            'title' => 'SSOT RFI',
            'subject' => 'SSOT RFI',
            'description' => 'Generated by SSOT fixture helper',
            'asked_by' => $user->id,
            'created_by' => $user->id,
            'assigned_to' => $user->id,
            'status' => 'open',
        ], $attributes));
    }

    protected function createDocumentFor(Tenant $tenant, Project $project, User $user, array $attributes = []): Document
    {
        return Document::factory()->create(array_merge([
            'tenant_id' => $tenant->id,
            'project_id' => $project->id,
            'uploaded_by' => $user->id,
            'created_by' => $user->id,
            'updated_by' => $user->id,
            'name' => 'ssot-document',
            'title' => 'SSOT Document',
            'original_name' => 'ssot-document.pdf',
            'file_path' => '/documents/ssot-document.pdf',
            'file_type' => 'pdf',
            'mime_type' => 'application/pdf',
            'file_size' => 1024,
            'file_hash' => md5((string) Str::ulid()),
        ], $attributes));
    }
}
