// Tập trung export tất cả các pages
export { default as LoginPage } from './auth/LoginPage';
export { default as DashboardPage } from './dashboard/DashboardPage';
export { default as ProjectsPage } from './projects/ProjectsPage';
export { default as ProjectDetailPage } from './projects/ProjectDetailPage';
export { default as CreateProjectPage } from './projects/CreateProjectPage';
export { default as TasksPage } from './tasks/TasksPage';
export { default as TaskDetailPage } from './tasks/TaskDetailPage';
export { default as ProfilePage } from './profile/ProfilePage';
export { default as SettingsPage } from './settings/SettingsPage';
export { default as NotFoundPage } from './errors/NotFoundPage';
export { default as UnauthorizedPage } from './errors/UnauthorizedPage';